### ISSUE TITLE
Feature request: Allow to filter out pull requests

### ISSUE THREAD

**Issue by graven** [rauhryan/huboard#126]
Our workflow involves creating an issue for each feature and then using multiple pull requests referencing this issue that contain shippable functionality. This means that at any given moment, there's more pull requests than actual issues/work items. It would be convenient to be able to hide pull requests from view.

Huboard marks pull requests on the board, which makes me think that this information is available. A possible way to implement this feature is in two steps:
 — Have a synthetic label in the left menu that looks and behaves like other labels, therefore allowing showing only pull requests;
 — Add fourth state to the label control, which removes the items with the chosen label from view.

**Comment by jack-kerouac** [comment]
:thumbsup:

**Comment by macrosak** [comment]
:thumbsup:

**Comment by lopesc** [comment]
(y)

**Comment by makoto-iguchi** [comment]
(y)

**Comment by discorick** [comment]
Close with #510
