### ISSUE TITLE
Fix visual artifacts on limited width screens

### ISSUE THREAD

**Issue by sgnn7** [rauhryan/huboard#170]
When working on a screen with limited width and many columns, various items get mangled

AC:
When given a large number of columns and small width:
- [ ] Column titles are not mangled
- [ ] Assigned person's icon is not over text
- [ ] Milestone is not mangled
- [ ] Issue numbers do not extend beyond the left border of the issue card
- [ ] Navigational column can be hidden/shrunk (optional)

Attached picture of current behavior stripped of irrelevant info:
![Example](https://f.cloud.github.com/assets/175811/539056/51961cfe-c1a2-11e2-8c5a-de4648fe9a9d.png)

**Comment by discorick** [comment]
Our UX has come a long way since then! Closing.
