### ISSUE TITLE
Lacking installation instructions

### ISSUE THREAD

**Issue by davidsteinsland** [rauhryan/huboard#275]
I managed to get Huboard installed using apache + mod_rails, but it took quite some time to get it done.

- Ruby 2.0 is required
- CouchDB install had to be done via the vagrant scripts (which are not in the stable release, but master)
- Lots of 404's to not-existing stylesheets and JS files
- Got a 404 on lib/auth/views/401.rb (it didn't exist, only in master)
- No mentioning that SSL is required in production, but there doesn't exist a config value to force development

Configuration was also a hazzle...

And for the most fun part: after spending hours setting it up, private repositories are a no go, even when hosted locally ...

**Comment by discorick** [comment]
Our wiki has been refreshed quite a few times since then https://github.com/rauhryan/huboard/wiki/Local-Development
