### ISSUE TITLE
Filter by multiple milestones feature request

### ISSUE THREAD

**Issue by parmy** [rauhryan/huboard#321]
One frustration we have with Github is being forced to filter by a single Milestone and then use Labels.

Is it possible to extend Huboard to allow multiple Milestones to be selected when filtering.

**Comment by discorick** [comment]
Closing as milestone filters can be combined

**Comment by mscheper** [comment]
@discorick: Can you point to docs for how to do this, please? When I go to a list of issues and click on 'Milestones ▼', I only seem to be able to select one milestone. I've read https://help.github.com/articles/search-syntax/ and https://github.com/koalyptus/TableFilter/wiki/4.-Filter-operators, but separating the names of two milestones with `||` does not work.

**Comment by discorick** [comment]
@mscheper , it sounds like you are describing the GitHub UI, filtering by multiple milestones is a [HuBoard](https://huboard.com/huboard/huboard) specific feature. 

Or are you trying to use `||` in the HuBoard search field?

**Comment by wxtim** [comment]
> Closing as milestone filters can be combined

Please could you post a link to to the documentation for this, because I cannot for the life of me work out _how_.
