### ISSUE TITLE
Add repository filter and add tasks to any linked repo

### ISSUE THREAD

**Issue by tslater** [rauhryan/huboard#330]
Combining repositories is a killer feature but is missing 2 *very* important features to be useful. We turned it off at my company. 
1) add a filter to show only tasks from a certain repository
2) When you create a new issue give an options of which of the current/linked repos to send it to.

**Comment by cwacek** [comment]
:+1: I concur. It means for moderately complex projects, issues effectively can't be added through huboard.

Seems like a relatively easy fix, just need to be able to pick the repo url and pass it into [here](https://github.com/rauhryan/huboard/blob/8af54eecab01a7209e2c338dd6fc61d5bbadd059/app/assets/javascripts/board/models/issue.js#L53), but I haven't had the time to dig in.

**Comment by discorick** [comment]
Filtering by repo, and creating issues on linked repos are both live! Closing.
