### ISSUE TITLE
Nothing tagged 'stable'

### ISSUE THREAD

**Issue by JorisBolsens** [rauhryan/huboard#347]
I am trying to follow the instructions to deploy huboard to heroku myself, one of the instructions is to use a version tagged as _stable_ however there is no branch named stable, nor are there any commits tagged as stable.

Where should I be looking for this, or what commit should I use?

**Comment by discorick** [comment]
The wiki for this has been refreshed, along with better default values in the example.env file. https://github.com/rauhryan/huboard/wiki/Local-Development
