### ISSUE TITLE
display connected commits / PRs in activity section

### ISSUE THREAD

**Issue by yoshokatana** [rauhryan/huboard#354]
It would be nice if referenced commits / PRs were displayed in the activity section, much like they are in github. Not sure if github's api allows that functionality, though.

[Like this](http://up.keats.me/image/1S0X2O2U2o2M)

**Comment by luebken** [comment]
+1

**Comment by ewoutp** [comment]
+1

**Comment by discorick** [comment]
We have commit references live at this point, and will be working on improving HuBoards handling of PR's very shortly!
