### ISSUE TITLE
Authentication issue with Enterprise

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#457]
After having signed out from GitHub or Huboard and trying to reopen Huboard using a bookmark we get the following error message: {"message":"Must authenticate to access this API."}. Instead, we should get a login to sign in.
We did some testing and this is when we have this message:
![error msg](https://cloud.githubusercontent.com/assets/5685914/5308582/61d95270-7bcd-11e4-853f-982279aac2f5.png)

**Comment by rauhryan** [comment]
Related to #470, should no longer be an issue when we handle log outs correctly
