### ISSUE TITLE
Access problems on a private repository with Safari 8.0.2

### ISSUE THREAD

**Issue by scharf** [rauhryan/huboard#462]
Today I installed the update to the newest Safari on MacOS 10.10.1 and now I have problems accessing a private repository that is owned my a co worker (I get a 404 error). 

I have no problem to access a public repository that I own.

With Chrome I have no problems accessing the private repository.

**Comment by 4eek** [comment]
@scharf I fixed it by clearing my History and Website data in Safari.

**Comment by discorick** [comment]
History > Clear History and Website Data fixes this for me as well.
