### ISSUE TITLE
Warning when I'm about to lose an unsaved comment.

### ISSUE THREAD

**Issue by lopesc** [rauhryan/huboard#475]
When adding a comment to a task on Huboard, I would like to be warned if I am about to lose my unsaved comment. Using Huboard Enterprise.

It is possible to close the task popover by clicking outside it.  It isn't clear that this means I will lose any unsaved changes.  Either I should not be allowed to close the popover by clicking outside - therefore I must click "Comment" - Or I should be warned that I am about to lose changes. 

Autosaving a comment is also a possibility but I'm not sure how desirable that is.  First and foremost, I do not want to lose my unsaved changes in case I closed the popover and assumed it was saved.

**Comment by rauhryan** [comment]
Hi @lopesc,

This is something that we are currently working on and should have been deployed to our SaaS version (huboard.com) yesterday. 

We are working on getting a HuBoard:Enterprise release ready, our next release will contain this fix.
