### ISSUE TITLE
Unsaved comment appears on all Tasks. 

### ISSUE THREAD

**Issue by lopesc** [rauhryan/huboard#476]
There is an issue where a user enters a comment in the Task popup and then closes the popover without saving the comment.  Using Huboard Enterprise.

To reproduce:

Open a task.
Enter a comment.
Click outside the popover to close it (do not saved the comment).
Open another task.
Notice that the comment which was entered for another task appears here.

**Comment by discorick** [comment]
Hi - a fix for this has been deployed to huboard.com, and should be included in the next Enterprise release!

**Comment by lopesc** [comment]
Thanks guys!
