### ISSUE TITLE
Add issue modal is sometimes gone after coming back from another tab

### ISSUE THREAD

**Issue by notmessenger** [rauhryan/huboard#497]
When creating new issues I will often open new tabs or visit already-open ones to gather necessary information for the issue's creation.  I have noticed that upon returning to the browser tab Huboard is loaded in, the add issue modal will randomly no longer be displayed.  This occurs whether there had been any information partially entered into the modal or not.  It did not save the issue - the modal is simply not displayed.

OS: OS X Yosemite - 10.10.2
Browser: Safari - Version 8.0.3 (10600.3.18)

**Comment by discorick** [comment]
One thing I would check is that you have "Allow from websites I visit" option selected in preferences - being unable to write to a cookie while communicating to an external source could potentially force a page refresh.

![pasted_image_2_12_15__6_48_pm](https://cloud.githubusercontent.com/assets/1130665/6180868/fe5d2cce-b2e7-11e4-8ac9-50f098343f36.png)
