### ISSUE TITLE
Check box not working in a comment

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#508]
We installed the last release of Huboard Enterprise this week-end (02-14-2015) and found out the check box are not working when they are in a comment. It work in the initial descrition.
It was working with the previous release.

**Comment by patdolem** [comment]
I forgot to say that it works only for the owner of the comment. I've added one below so you can check if it works.
- [ ] Test

**Comment by discorick** [comment]
Thanks for the catch, it appears a change we made to issue permissions caused this, we'll push up a fix for this next release!

**Comment by patdolem** [comment]
Do you have an idea on when this next release will be available?

**Comment by rauhryan** [comment]
@patdolem We've tracked it down, it's an easy fix, once @discorick fixes it I'll package up a new HB:E release right away
