### ISSUE TITLE
Add commit status to card (pending, success, failed, etc)

### ISSUE THREAD

**Issue by wireframe** [rauhryan/huboard#523]
It would be great to have an indicator on the card in huboard if a pull request has passed/failed/pending to know when it can be moved to the next lane.

**Comment by rauhryan** [comment]
Hey @wireframe just released this feature as part of huboard/huboard-web#93 

![uploads/333b4644-70ff-425f-b8d3-94c3c5f4ceed/rauhryan_ghee_test_HuBoard_and_rauhryan_ghee_test_HuBoard.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F333b4644-70ff-425f-b8d3-94c3c5f4ceed%2Frauhryan_ghee_test_HuBoard_and_rauhryan_ghee_test_HuBoard.png)

I'd appreciate your feedback
