### ISSUE TITLE
Close notification happens twice when closed via Huboard

### ISSUE THREAD

**Issue by seanlinsley** [rauhryan/huboard#531]
The result as seen in our Slack room:

<img width=80% src=https://cloud.githubusercontent.com/assets/688886/6848539/e207d7fc-d39b-11e4-8dae-640530d3ee22.png>

**Comment by discorick** [comment]
We recently made some changes to how we fire off events, it appears a couple of them are doubling up with Github webhooks.

**Comment by rauhryan** [comment]
A fix should be deployed
