### ISSUE TITLE
Allow to create an issue for a linked project

### ISSUE THREAD

**Issue by ZenCocoon** [rauhryan/huboard#532]
Working with linked project is wonderful, though it would be awesome to be able to create a new ticket for one of this linked repo.
A select box with default to the current "top" project would be great I think.

**Comment by discorick** [comment]
Good idea - I like the idea of being able to switch the context of the repo you are creating an issue for (providing you are a collaborator if it is a private repo)

**Comment by discorick** [comment]
@ZenCocoon this was released late last week!
