### ISSUE TITLE
Bug: When milestone of card is modified the main views are not updated

### ISSUE THREAD

**Issue by ck--** [rauhryan/huboard#534]

**Comment by discorick** [comment]
This is something our team has spent some time discussing - Github does not send a webhook event when a milestone is changed, so it is difficult for us to capture those edits in real time. We are working on a solution that should help us 'fill in the gaps' where GH's webhooks don't reach.

**Comment by ck--** [comment]
No I mean only when I modify something in huboard. I understand that it is not that easy when modified only in github.

**Comment by discorick** [comment]
Ok gotcha - would you be able to provide me some details on how to reproduce?

**Comment by ck--** [comment]
Very easy: open an issue in huboard. Select a milestone. Close the dialog.
But the view in huboard is not updated. It does not recognize the
modification on the milestone.

You have to do a page reload in order to update.
Am 08.04.2015 22:44 schrieb "discorick" <notifications@github.com>:

**Comment by discorick** [comment]
Interesting, I am testing and all my cards are snapping properly to the assigned milestones - what browser & OS are you using ?

**Comment by discorick** [comment]
The board should now stay in sync when changing milestones.
