### ISSUE TITLE
I'm unable to pay

### ISSUE THREAD

**Issue by dskarataev** [rauhryan/huboard#535]
Hi. I'm trying to pay with stripe using my credit card. I push the button Upgrade and I put my credit card information to the form. Then I push the button "Pay with Stripe". Then I get the message that my account is activated but actually it's a fake message. Because my account balance is same and also if I update page I get message that my account is expired again.

Please check with my organization "tterp"

**Comment by discorick** [comment]
Hi there, in order to avoid posting private information on a public issue, would you be able to fire an email to support@huboard.com where we can troubleshoot this further for you?
