### ISSUE TITLE
ember issue

### ISSUE THREAD

**Issue by trevorwang** [rauhryan/huboard#536]
tried to build javascript following wiki.
got the error

version: 0.2.3
You have to be inside an ember-cli project in order to use the build command.

**Comment by discorick** [comment]
Do you have ember-cli installed globally ? Currently HuBoard is using ember-tools (which could be why you are receiving the error) We are however nearly finished migrating the app over to ember-cli which should simplify the build process (you can track our progress on https://github.com/huboard/huboard-web)

The huboard-web repo will soon be played over the current rauhryan/huboard repo.

**Comment by discorick** [comment]
Refreshed wiki instructions should make this more straightforward: https://github.com/rauhryan/huboard/wiki/Local-Development
