### ISSUE TITLE
Updating assignee, labels or milestone need a click to refresh when filters are on

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#547]
When updating assignee, labels or milestone for an issue, it needs a click on one of the filter to refresh the screen. Refresh should be immediate.

**Comment by patdolem** [comment]
v1.6.93 release fix partly this issue. It only works for the team members.

**Comment by discorick** [comment]
Hey @patdolem I am having troubles reproducing, what are the steps I need to take to recreate this behavior ?

**Comment by patdolem** [comment]
@discorick This is not working for the milestone. I forgot to mention that it also works for the labels.
These are the steps:
1. Filter to a given milestone
2. Open an issue
3. Add/replace to another milestone
4. Close the issue
Nothing happened while I expect the issue to disappear from my list (this is the way it works when a filter is set to an assignee when re-assigning an issue to another one).

**Comment by discorick** [comment]
@patdolem Aha! I see what you mean, i'll make sure its taken care of for next release

**Comment by patdolem** [comment]
It works well now. Closing this issue.
