### ISSUE TITLE
Edit text field too small

### ISSUE THREAD

**Issue by brik** [rauhryan/huboard#558]
I think the edit text field became smaller with the last upgrade. 

It would be nice if it was bigger by default or if there was a way to expand the field. Right now it's pretty annoying if you're editing more than a few lines of text and I find myself going back to github to add or edit comments.

Btw: I am using Chrome

**Comment by DanielCaldwell** [comment]
Same here... It's only about 3 lines.

**Comment by rauhryan** [comment]
Ah ok, 

At some point this got broken, likely with an ember upgrade we did recently. 

It used to autogrow as you typed similar to the facebook text areas.

We'll take a look soon. 

Sorry

**Comment by brik** [comment]
Great, thanks!

**Comment by discorick** [comment]
Text fields not auto-growing has been fixed, closing

**Comment by DanielCaldwell** [comment]
thanks!
