### ISSUE TITLE
the ssl certificate on huboard.com has expired

### ISSUE THREAD

**Issue by AntiSol** [rauhryan/huboard#562]
Please renew your SSL certificate

Further, firefox says "This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.", meaning that I'm currently not able to access the site at all

thanks

**Comment by arw180** [comment]
+1

**Comment by rauhryan** [comment]
Done! 

Sorry about that everyone
