### ISSUE TITLE
Label changes made in Github wont sync without reloading Huboard

### ISSUE THREAD

**Issue by ehausen** [rauhryan/huboard#564]
When adding or removing Labels on Github the changes wont sync with Huboard until Huboard is reloaded manually. It is now possible that someone edits a Github issue and then someone else edits the same issue on Huboard and Huboard overwrites with its version of things. 

This effectively makes it quite impossible to let anyone use the Github issue tracker, which is kind of one point of having a issue manager at the top of Huboard. Now you can use only Huboard.

Similar issue is #301 

There @rauhryan states that it is currently not possible to sync in real time. But waffle.io seems to have come up with some way - you get a notification and changes are synced to waffle right away after label changes are made on Github. 

Quick workaround solution suggestions
* check for (All) changes (and sync) when opening a issue card
* check for changes before saving the card

**Comment by ehausen** [comment]
Actually Waffle seems to do the above suggested things when detecting changed **title** changes (checking for changes when opening/editing), but **label** changes are instantly detected somehow

**Comment by ehausen** [comment]
Labels on Github seem to be overwritten only when actually changing labels on Huboard. Not when commenting or doing other stuff with the issue for example.

**Comment by ehausen** [comment]
#214

**Comment by discorick** [comment]
Currently the only way for use to detect changes on labels from GitHub is by polling their API for them directly (there are no incoming events for label unfortunately) HuBoards primary constraint in this area is we do not use a persistent data store to assemble the board, or a poller to detect changes real time. Once we have a poller in place this should become a relatively easy problem to address.
