### ISSUE TITLE
Issue created on Github won't sync to Huboard automatically

### ISSUE THREAD

**Issue by ehausen** [rauhryan/huboard#565]
- Create a new issue on Github
- Go to Huboard and observe that it is nowhere
- If you reload Huboard the new issue appears
- You can comment and add labels on github, but the card doesn't appear on Huboard before manual reload of page

**Comment by ehausen** [comment]
#214 
Is this dublicate?

**Comment by discorick** [comment]
PR https://github.com/huboard/huboard-web/pull/88
