### ISSUE TITLE
Github integration is now only partial

### ISSUE THREAD

**Issue by ehausen** [rauhryan/huboard#566]
I'm wondering why you decided to add features that can not be changed or viewed on Github, but still there are some things you can change on Github. 

For example you have added  *Ready for next stage* and *Blocked* as checkboxes that are then saved to Github as a hidden comment `<!--- @huboard {"order":11.5,"milestone_order":15,"custom_state":"ready"}-->` in the initial comment of the issue

This is custom state doesn't show up in Github and can't be changed there (well other than editing that hidden comment I guess). Wouldn't it be much better to just have the checkboxes or other custom things as Github Labels like columns now are? Why would you partially use the Github features like tags, but then have something else that can not be controlled on Github?

This means that now you can actually only use Huboard and can't let anyone use Github to edit/add issues. (Also because it doesn't sync new issues #565, labels changed #564 or titles #301 changed at all without reloading). 

I think it would be ideal that it would still be possible to use Github issues. If you are inventing your own feature that are incompatible/invisible on Github, then you could just save it all as JSON or in own issue database.

**Comment by discorick** [comment]
Re: Ready/Blocked checkboxes, we are working on adding a label that stays in sync with the meta-data, I agree its good to keep data as consistent as possible between platforms. You can track progress at #399

Ill address #565, #564 and #301 within their own issue threads, @ehausen thanks by the way for the detailed feedback, its appreciated. (sorry about the late response, we are a little behind on keeping up with the backlog)
