### ISSUE TITLE
[Missing] Milestone Column Reorder Socket Event

### ISSUE THREAD

**Issue by discorick** [rauhryan/huboard#576]

**Comment by rauhryan** [comment]
[BLOCKED] blocked until we can release and refactor the model layout 

all the ground work is done and the client is receiving the event 

https://github.com/huboard/huboard-web/commit/cc61da003d45aaf674d08934d4759e7445e572b8

**Comment by discorick** [comment]
Unblocked now that we have client side messaging hooked up.
