### ISSUE TITLE
Pull request is not showing up on issue page

### ISSUE THREAD

**Issue by tvsonar** [rauhryan/huboard#579]
When you view an issue on the HuBoard UI, only the comments belonging to the issue are showing up. It would be nice to have the pull requests as well.

Typically, when you implement/fix an issue, you do that in a separate branch, and then a PR. To review the issue, you need to go to the PR, but at the moment there is no direct link for that. First you need to open the issue on GitHub, and there you can follow the PR reference.

**Comment by discorick** [comment]
merging into #354, ill offer up an update there!
