### ISSUE TITLE
add issue - select repository from linked

### ISSUE THREAD

**Issue by misterfitz** [rauhryan/huboard#595]
Would be great to be able to select a linked repository to create a new issue in.

**Comment by rauhryan** [comment]
![huboard_and_huboard_and_add_issue_-_select_repository_from_linked_ _issue__595_ _rauhryan_huboard_and_slack](https://cloud.githubusercontent.com/assets/68954/10147282/b54692c8-65f2-11e5-9ce8-53a5c52e28f2.png)

You can specify more details if you click the + button

**Comment by misterfitz** [comment]
Interesting - we must be on an old version as I don't see this option. I do have the latest version available from https://enterprise.huboard.com/

**Comment by rauhryan** [comment]
It's possible you are running into a problem while upgrading. 

The latest package file from enterprise.huboard.com should have this feature

**Comment by rauhryan** [comment]
@misterfitz email me and we can set up a time to screenshare
