### ISSUE TITLE
Urgent - Team member filtering is not working properly since 1.6.94 (Huboard Enterprise)

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#600]
Team member filtering is working inconsistently. For some teams, one or many members are not showing up. This is happening since we installed Huboard Enterprise 1.6.94

**Comment by discorick** [comment]
Hey @patdolem, I will look into this ASAP - when you say members are not showing up are you referring to the active members thumbnail missing members you would expect to be there ?

**Comment by patdolem** [comment]
@discorick Thumbnails are showing in the individual tasks but the filter panel only lists a part of the active team members.
![teammembers](https://cloud.githubusercontent.com/assets/5685914/10738383/70a8d278-7bd4-11e5-8dc8-0b4b6d5f1805.png)

**Comment by discorick** [comment]
Ok I see the problem! Thanks for heads up we will make sure to patch this right away!
